#include "main.h"
#include <string.h>

#include "ROOT.h"
#include "DBUS.h"
#include "MOTOR.h"
#include "TIM_DEV.h"
#include "DEFINE.h"
#include "YU_PID.h"
#include "ATTACK.h"
#include "TOP.h"

uint8_t ROOT_V_MONITOR_DBUS = 0; // 离线判断参数
TYPEDEF_MOTOR_PID FOLLOW_PID = {0};
TYPEDEF_MOTOR_PID TOP_OFF_S = {0}, TOP_OFF_A = {0};

void ROOT_F_MONITOR_DBUS(TYPEDEF_DBUS *DBUS)
{
    ROOT_V_MONITOR_DBUS++;

    if (ROOT_V_MONITOR_DBUS >= 50) // 50ms
    {
        memset(&DBUS_V_DATA, 0, sizeof(DBUS_V_DATA));
        memset(MOTOR_V_CHASSIS, 0, sizeof(MOTOR_V_CHASSIS));
        memset(MOTOR_V_GIMBAL, 0, sizeof(MOTOR_V_GIMBAL));
        memset(MOTOR_V_ATTACK, 0, sizeof(MOTOR_V_ATTACK));
    }
}

// 传pid参数
uint8_t ROOT_F_PIDinit()
{
    const float PID_V_CHASSIS_SPEED[5] = {15.0f, 0.0f, 0, 2000.0f, 30000.0f};
    const float PID_V_CHASSIS_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

	const float PID_V_GIMBAL_YAW_SPEED[5] = {375.0f, 0.0f, 0, 100.0f, 30000.0f};
    const float PID_V_GIMBAL_YAW_ANGLE[5] = {1.35f, 0.0f, 0.0f, 200.0f, 2000.0f};
	// const float PID_V_GIMBAL_YAW_SPEED[5] = {100.0f, 0.0f, 20.0f, 100.0f, 30000.0f};
    // const float PID_V_GIMBAL_YAW_ANGLE[5] = {0.8f, 0.0f, 0.0f, 200.0f, 657.0f};
    const float PID_V_GIMBAL_PIT_SPEED[5] = {20.22f, 0.001f, 0, 1000.0f, 20000.0f};
    const float PID_V_GIMBAL_PIT_ANGLE[5] = {10.0f, 0, 0, 1000.0f, 3000.0f};

    const float PID_V_ATTACK_L_SPEED[5] = {5.0f, 0, 0, 1000.0f, 20000.0f};
    const float PID_V_ATTACK_R_SPEED[5] = {5.0f, 0, 0, 1000.0f, 20000.0f};
    const float PID_V_ATTACK_G_SPEED[5] = {10.0f, 0, 0, 1000.0f, 8000.0f};
    const float PID_V_ATTACK_G_ANGLE[5] = {1.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_L_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_R_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

    const float FOLLOW_PID_V[5] = {1.5f, 0.0f, 0.0f, 0.0f, 2000.0f};
    const float PID_V_TOP_OFF_S[5] = {100.5f, 0.0f, 0.0f, 0.0f, 30000.0f};
    const float PID_V_TOP_OFF_A[5] = {1.5f, 0.0f, 0.0f, 0.0f, 2000.0f};

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_S, PID_V_CHASSIS_SPEED);

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_C, PID_V_CHASSIS_CURRENT);

    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_S, PID_V_GIMBAL_YAW_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_A, PID_V_GIMBAL_YAW_ANGLE);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_S, PID_V_GIMBAL_PIT_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_A, PID_V_GIMBAL_PIT_ANGLE);

    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_S, PID_V_ATTACK_L_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_S, PID_V_ATTACK_R_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_S, PID_V_ATTACK_G_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_A, PID_V_ATTACK_G_ANGLE);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_C, PID_V_ATTACK_L_CURRENT);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_C, PID_V_ATTACK_R_CURRENT);

    PID_F_Init(&FOLLOW_PID, FOLLOW_PID_V);
    PID_F_Init(&TOP_OFF_S, PID_V_TOP_OFF_S);
    PID_F_Init(&TOP_OFF_A, PID_V_TOP_OFF_A);
    return ROOT_READY;
}

void ROOT_F_Init()
{
    ROOT_F_PIDinit();
	MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.ANGLE_INIT = 1314 + 4096;  // 云台初始化角度
	MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.AIM = (float)MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.ANGLE_INIT;
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].DATA.AIM = 5000.0f;
    
	MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.LAPS = 1;   // @TODO when yaw init, aim 0->angle_init, make yaw shaking.
	
    ATTACK_F_Init(MOTOR_V_ATTACK);
    
}