#include "main.h"
#include <string.h>

#include "ROOT.h"
#include "DBUS.h"
#include "MOTOR.h"
#include "TIM_DEV.h"
#include "DEFINE.h"
#include "YU_PID.h"
#include "ATTACK.h"
#include "TOP.h"
    
uint8_t ROOT_V_MONITOR_DBUS = 0; // 离线判断参数
TYPEDEF_MOTOR_PID FOLLOW_PID = {0};  // 底盘跟随
TYPEDEF_MOTOR_PID TOP_OFF_S = {0}, TOP_OFF_A = {0}; // 陀螺仪离线，但因时间短，可考虑删除
TYPEDEF_MOTOR_PID VISION_PID_YAW_SPEED;         // 视觉PID
TYPEDEF_MOTOR_PID VISION_PID_YAW_ANGLE;
TYPEDEF_MOTOR_PID VISION_PID_PIT_SPEED;
TYPEDEF_MOTOR_PID VISION_PID_PIT_ANGLE;

void ROOT_F_MONITOR_DBUS(TYPEDEF_DBUS *DBUS)
{
    ROOT_V_MONITOR_DBUS++;

    if (ROOT_V_MONITOR_DBUS >= 50) // 50ms
    {
        DBUS_F_Offline(DBUS);
    }
}

// 传pid参数
uint8_t ROOT_F_PIDinit()
{
    const float PID_V_CHASSIS_SPEED[5] = {15.0f, 0.0f, 0, 2000.0f, 30000.0f};
    const float PID_V_CHASSIS_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

	// const float PID_V_GIMBAL_YAW_SPEED[5] = {375.0f, 0.0f, 0, 100.0f, 30000.0f};
    // const float PID_V_GIMBAL_YAW_ANGLE[5] = {1.35f, 0.0f, 0.0f, 200.0f, 2000.0f};
	//const float PID_V_GIMBAL_YAW_SPEED[5] = {600.0f, 0.0f, 0.5f, 100.0f, 10000.0f};//正常值
//	const float PID_V_GIMBAL_YAW_SPEED[5] = {17.0f, 0.0f, 0.5f, 100.0f, 10000.0f};//正常值
//    const float PID_V_GIMBAL_YAW_ANGLE[5] = {9.0f, 0.0f, 0.0f, 200.0f, 5000.0f};
    const float PID_V_GIMBAL_YAW_SPEED[5] = {400.0f, 0.0f, 0.5f, 100.0f, 10000.0f};//正常值
    const float PID_V_GIMBAL_YAW_ANGLE[5] = {0.36f, 0.0f, 0.0f, 200.0f, 2000.0f};
//    const float PID_V_GIMBAL_PIT_SPEED[5] = {130.0f, 0.0f, 0, 1000.0f, 20000.0f};
//    const float PID_V_GIMBAL_PIT_ANGLE[5] = {0.85f, 0.0007f, 0, 1000.0f, 3000.0f};
	const float PID_V_GIMBAL_PIT_SPEED[5] = {100.0f, 20.0f, 0, 2000.0f, 30000.0f};
    const float PID_V_GIMBAL_PIT_ANGLE[5] = {1.625f, 0.045f, 0.0f, 200.0f, 7000.0f};
	
    const float PID_V_ATTACK_L_SPEED[5] = {14.0f, 0, 0, 1000.0f, 30000.0f};
    const float PID_V_ATTACK_R_SPEED[5] = {14.0f, 0, 0, 1000.0f, 30000.0f};
    const float PID_V_ATTACK_G_SPEED[5] = {10.0f, 0, 0, 1000.0f, 20000.0f};
    const float PID_V_ATTACK_G_ANGLE[5] = {1.0f, 0, 0, 1000.0f, 4500.0f};  // 拨盘角度AIM控制弹频，3000-13.3Hz,4500-16.99Hz,5000(2single)-23.3Hz占比约1/3
    const float PID_V_ATTACK_L_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_R_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

    const float FOLLOW_PID_V[5] = {2.0f, 0.0f, 0.0f, 0.0f, 3500.0f};
    const float PID_V_TOP_OFF_S[5] = {100.5f, 0.0f, 0.0f, 0.0f, 30000.0f};
    const float PID_V_TOP_OFF_A[5] = {1.5f, 0.0f, 0.0f, 0.0f, 2000.0f};

    const float PID_V_VISION_YAW_SPEED[5] = {300.0f, 0.0f, 70.0f, 0.0f, 29000.0f};
    const float PID_V_VISION_YAW_ANGLE[5] = {3.80f, 0.0f, 10.0f, 0.0f, 10000.0f};
    const float PID_V_VISION_PIT_SPEED[5] = {380.0f, 0.02f, 0, 1000.0f, 30000.0f};
    const float PID_V_VISION_PIT_ANGLE[5] = {6.0f, 0.0f, 0, 1000.0f, 10000.0f};

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_S, PID_V_CHASSIS_SPEED);

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_C, PID_V_CHASSIS_CURRENT);

    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_S, PID_V_GIMBAL_YAW_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_A, PID_V_GIMBAL_YAW_ANGLE);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_S, PID_V_GIMBAL_PIT_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_A, PID_V_GIMBAL_PIT_ANGLE);

    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_S, PID_V_ATTACK_L_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_S, PID_V_ATTACK_R_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_S, PID_V_ATTACK_G_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_A, PID_V_ATTACK_G_ANGLE);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_C, PID_V_ATTACK_L_CURRENT);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_C, PID_V_ATTACK_R_CURRENT);

    PID_F_Init(&FOLLOW_PID, FOLLOW_PID_V);
    PID_F_Init(&TOP_OFF_S, PID_V_TOP_OFF_S);
    PID_F_Init(&TOP_OFF_A, PID_V_TOP_OFF_A);
    PID_F_Init(&VISION_PID_YAW_SPEED, PID_V_VISION_YAW_SPEED);
    PID_F_Init(&VISION_PID_YAW_ANGLE, PID_V_VISION_YAW_ANGLE);
    PID_F_Init(&VISION_PID_PIT_SPEED, PID_V_VISION_PIT_SPEED);
    PID_F_Init(&VISION_PID_PIT_ANGLE, PID_V_VISION_PIT_ANGLE);
    return ROOT_READY;
}

void ROOT_F_Init()
{
    ROOT_F_PIDinit();
    ATTACK_F_Init(MOTOR_V_ATTACK);

    #ifdef OLDHEAD
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.ANGLE_INIT = 3422.0f + 4096.0f;  // 云台初始化角度
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].DATA.AIM = 2807.0f;
	MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.LAPS = 1;   // @TODO when yaw init, aim 0->angle_init, make yaw shaking.
	#endif

    #ifdef OMNI
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.ANGLE_INIT = 1314 + 4096;
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].DATA.AIM = 3000.0f;
    MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.LAPS = 1; 
    // pid反馈值取自编码器时电机能够上电稳定到对应位置，取自陀螺仪则注释
	// MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.AIM = (float)MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].DATA.ANGLE_INIT;
    #endif
}