#include "main.h"
#include <string.h>

#include "ROOT.h"
#include "DBUS.h"
#include "MOTOR.h"
#include "TIM_DEV.h"
#include "DEFINE.h"
#include "PID.h"

uint8_t ROOT_V_MONITOR_DBUS = 0; // 离线判断参数

void ROOT_F_MONITOR_DBUS(TYPEDEF_DBUS *DBUS)
{
    ROOT_V_MONITOR_DBUS++;
    if (ROOT_V_MONITOR_DBUS >= 50)
    {
        memset(&DBUS_V_DATA, 0, sizeof(DBUS_V_DATA));
    }
}

// 传pid参数
void ROOT_F_PIDinit()
{
    const float PID_V_CHASSIS_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_CHASSIS_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

    const float PID_V_GIMBAL_YAW_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_GIMBAL_YAW_ANGLE[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_GIMBAL_PIT_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_GIMBAL_PIT_ANGLE[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

    const float PID_V_ATTACK_L_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_R_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_G_SPEED[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_G_ANGLE[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_L_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};
    const float PID_V_ATTACK_R_CURRENT[5] = {3.0f, 0, 0, 1000.0f, 3000.0f};

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_S, PID_V_CHASSIS_SPEED);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_S, PID_V_CHASSIS_SPEED);

    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_1].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_2].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_3].PID_C, PID_V_CHASSIS_CURRENT);
    PID_F_Init(&MOTOR_V_CHASSIS[MOTOR_D_CHASSIS_4].PID_C, PID_V_CHASSIS_CURRENT);

    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_S, PID_V_GIMBAL_YAW_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_YAW].PID_A, PID_V_GIMBAL_YAW_ANGLE);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_S, PID_V_GIMBAL_PIT_SPEED);
    PID_F_Init(&MOTOR_V_GIMBAL[MOTOR_D_GIMBAL_PIT].PID_A, PID_V_GIMBAL_PIT_ANGLE);

    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_S, PID_V_ATTACK_L_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_S, PID_V_ATTACK_R_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_S, PID_V_ATTACK_G_SPEED);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_G].PID_A, PID_V_ATTACK_G_ANGLE);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_L].PID_C, PID_V_ATTACK_L_CURRENT);
    PID_F_Init(&MOTOR_V_ATTACK[MOTOR_D_ATTACK_R].PID_C, PID_V_ATTACK_R_CURRENT);
}

void ROOT_F_Init()
{
    ROOT_F_PIDinit();

    MOTOR_V_ATTACK[MOTOR_D_GIMBAL_PIT].DATA.AIM = 4500;
}