# name: Upload to Debug Branch

# on:
#     push:
#       branches:
#         - oldHead # All branches
#     schedule:
#       - cron: '0 0 * * *' # Every day at 00:00s

# jobs:
#   upload:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.GITEA_SSH_PRIVATE_KEY }}

#     - name: Push to Gitea
#       run: |
#         git remote add gitea ssh://git@your-gitea-instance.com:222/username/repo.git
#         git push gitea main