name: Sync Local Repository

on:
  schedule:
    - cron: '23 13 * * *' # 每小时运行一次
  push:
    branches:
      - main

jobs:
  # sync:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Git
  #     run: |
  #       git config --global user.name ${{ secrets.USERNAME }}
  #       git config --global user.email ${{ secrets.EMAIL }}

  #   - name: Sync with local repository
  #     run: |
  #       git remote add local /path/to/your/local/repository
  #       git fetch local
  #       git merge local/main
  #       git push https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/Cofallen/OMNI_C.git main

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Git 用户信息
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: 添加更改
        run: |
          git add .

      - name: 提交更改
        run: |
          git commit -m "update" || echo "没有更改需要提交"

      - name: 推送到 GitHub
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
